---
kind: pipeline
type: docker
name: powerdns

steps:

- name: deploy_local
  pull: never
  image: ${DCAPE_COMPOSE}
  commands:
  - . setup config
  - make update
  volumes:
  - name: dockersock
    path: /var/run/docker.sock

volumes:
- name: dockersock
  host:
    path: /var/run/docker.sock

# docker run powerdns pdnsutil check-zone
