SHELL = /bin/bash
CFG=.env
SOURCES=$(wildcard *.sql)
OBJECTS=$(SOURCES:.sql=.done)

all: $(CFG) $(OBJECTS)

up: all

%.done: %.sql
	@echo "*** $< ***"
	@cat $< | docker exec -i $$PG_CONTAINER psql -U $$PG_USER > $@

clean:
	rm -rf *.done

# шаблон файла .env

define CONFIG_DEF
# dcape-dns-config $(CFG) file, generated by make $(CFG)

# Postgresql container name
PG_CONTAINER=dcape_db_1

# PowerDNS DB user (and database) name
PG_USER=dns
endef
export CONFIG_DEF

$(CFG):
	@echo "*** $@ ***"
	@[ -f $@ ] || { echo "$$CONFIG_DEF" > $@ ; echo >&2 "Warning: Created default $@" ; }
